location:
  name: "Castelbaldo"
  latitude: 45.00
  longitude: 11.28

services:
  dpc: true
  arpav: true
  openmeteo: true

mqtt:
  broker: "mqtt-broker-url"
  topic_prefix: "homeassistant/sensor"
  username: "mqtt_user"
  password: "mqtt_password"
