name: Update Meteo Data

on:
  schedule:
    - cron: "*/5 * * * *"   # ogni 5 minuti
  workflow_dispatch:         # permette esecuzione manuale

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        run: |
          cd src
          python main_pipeline.py
